spring.application.name=Karaikadeeshwarar

spring.datasource.url=jdbc:mysql://reseau.proxy.rlwy.net:32314/railway
spring.datasource.username=root
spring.datasource.password=arIvrTdLlPUfvXcLvteBLjvZABrnVQQD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mysecretmysecretmysecretmysecret123456789
jwt.expiration=86400000

server.port=${PORT:8080}
